//
//  LocalShoutout.swift
//  
//
//  Created by Marcos Morais on 22/08/22.
//

import Foundation
import UserNotifications
import OSLog

/**
 The LocalShoutoutCenter is the class you need to create, schedule and cancel notifications.
 */
open class LocalShoutoutCenter {

    /// The instance of the current UNUserNotificationCenter.
    internal let currentNotificationCenter = UNUserNotificationCenter.current()
    /// A logger for internal purposes.
    internal let logger = Logger(subsystem: "LocalShoutout", category: "LocalNotifications")
    
    /// The authenticated flag  determines if the user granted the app permission to send notifications.
    public var authenticated: Bool = false
    /// A delegate that can be assigned so that you have access to all events generated by the LocalShoutoutCenter.
    public weak var delegate: ShoutableDelegate?
    
    // MARK: - Initializer
    public init() {
        self.getAuthenticationStatus()
        delegate?.centerDidStart(center: self)
    }
    
}

/**
 Convenience methods for LocalShoutoutCenter.
 */
extension LocalShoutoutCenter {
    internal func getAuthenticationStatus() {
        self.currentNotificationCenter.getNotificationSettings { settings in
            switch settings.authorizationStatus {
            case .authorized:
                self.authenticated = true
            default:
                self.authenticated = false
            }
        }
    }
    
    internal func fetchSoundUsing(_ notification: NotificationData) -> UNNotificationSound {
        if notification.hasSound {
            #if os(watchOS)
            // watchOS is not compatible with custom UNNotificationSound(named)
            #else
            let sound = UNNotificationSound(named: UNNotificationSoundName(rawValue: notification.sound.orEmpty))
            return sound
            #endif
        }
        return UNNotificationSound.default
    }
    
    internal func buildNotificationContentByUsing(_ notification: NotificationData) -> UNNotificationContent {
        let content = UNMutableNotificationContent()
        content.title = notification.title
        content.body = notification.body
        content.sound = self.fetchSoundUsing(notification)
        return content
    }
}
